version: "2"
services:
    bbs_front:
        build:
            context: ./Front
            dockerfile: Dockerfile
            args:
                domain: http://localhost:7010/
        ports:
            - 8080:80
    bbs:
        build: ./
        ports:
            - 7010:7010
            - 7011:7011
        command:
            - run
            - init
        volumes:
            - D:/bbs:/var/bbs
        restart: always
        depends_on:
            - prisma
            - redis
    prisma:
        image: prismagraphql/prisma:1.21
        environment:
            PRISMA_CONFIG: |-
                port: 4466
                databases:
                  default:
                    connector: mysql
                    host: mysql
                    port: 3306
                    user: root
                    password: P@ssw0rd
                    migrations: true
        stdin_open: true
        tty: true
        depends_on:
            - mysql
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
        stdin_open: true
        tty: true
    redis:
        image: redis
        stdin_open: true
        tty: true
